// MockUsers.jsx
export const USERS_DATABASE = [
  {
    id: 1,
    employeeid: "ADM001",
    firstName: "John",
    lastName: "Doe",
    name: "John Doe",
    position: "Admin",
    role: "Admin",
    email: "john.doe@example.com",
    contact_number: "09171234567",
    department: "IT",
    birthDate: "1995-04-15",
    created_at: "2023-08-15",
    profileImage: "https://i.pravatar.cc/100?img=1", // Changed from "avatar"
    username: "admin",
    password: "1234",
    branch: "Metrobank Fort - Ecoprime Tower"
  },
  {
    id: 2,
    employeeid: "ADM002",
    firstName: "Jane",
    lastName: "Smith",
    name: "Jane Smith",
    position: "Admin",
    role: "Admin",
    email: "jane.smith@example.com",
    contact_number: "09181234567",
    department: "HR",
    birthDate: "1990-08-20",
    created_at: "2023-09-01",
    profileImage: "https://i.pravatar.cc/100?img=2",
    username: "admin2",
    password: "password123",
    branch: "Metrobank Fort - Mckinley Branch"
  },
  {
    id: 3,
    employeeid: "SEO003",
    firstName: "Mike",
    lastName: "Johnson",
    name: "Mike Johnson",
    position: "Senior Executive Employee",
    role: "Senior Executive Officer",
    email: "mike.johnson@example.com",
    contact_number: "09191234567",
    department: "Senior Executive Officer",
    birthDate: "1988-03-12",
    created_at: "2023-07-20",
    profileImage: "https://i.pravatar.cc/100?img=3",
    username: "seo1",
    password: "1234",
    branch: "Metrobank Fort - Ecoprime Tower"
  },
  {
    id: 4,
    employeeid: "SEO004",
    firstName: "Sarah",
    lastName: "Wilson",
    name: "Sarah Wilson",
    position: "Senior Executive Officer",
    role: "Senior Executive Officer",
    email: "sarah.wilson@example.com",
    contact_number: "09201234567",
    department: "Operations",
    birthDate: "1992-11-08",
    created_at: "2023-10-12",
    profileImage: "https://i.pravatar.cc/100?img=4",
    username: "seo2",
    password: "1234",
    branch: "Metrobank Fort - Mckinley Branch"
  }
];